# Generated by Django 5.1.7 on 2025-04-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
