# Generated by Django 5.1.7 on 2025-04-06 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_feedback_admin_notes_feedback_is_active'),
        ('clinic', '0005_alter_appointment_patient_name'),
    ]

    operations = [
    ]
